EUROPEAN_GEOS = {
    "EU27_2020": "UE27",
    "EA20": "Area euro",
    "AT": "Austria",
    "BE": "Belgio",
    "BG": "Bulgaria",
    "HR": "Croazia",
    "CY": "Cipro",
    "CZ": "Cechia",
    "DK": "Danimarca",
    "EE": "Estonia",
    "FI": "Finlandia",
    "FR": "Francia",
    "DE": "Germania",
    "EL": "Grecia",
    "HU": "Ungheria",
    "IE": "Irlanda",
    "IT": "Italia",
    "LV": "Lettonia",
    "LT": "Lituania",
    "LU": "Lussemburgo",
    "MT": "Malta",
    "NL": "Paesi Bassi",
    "PL": "Polonia",
    "PT": "Portogallo",
    "RO": "Romania",
    "SK": "Slovacchia",
    "SI": "Slovenia",
    "ES": "Spagna",
    "SE": "Svezia",
    "NO": "Norvegia",
    "IS": "Islanda",
    "CH": "Svizzera",
}
